students/urls.py
from django.conf.urls import patterns, url

from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add_student/$', views.StudentCreateView.as_view(), name='add_student'),
    url(r'^edit_student/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit_student'),
    url(r'^delete_student/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='delete_student'),
)

students/models.py
from django.db import models
from courses.models import Course


class Student(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    date_of_birth = models.DateField(null=True) # DateField
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    skype = models.CharField(max_length=255)
    courses = models.ManyToManyField(Course)

    def __unicode__(self):
        return u'{} {}'.format(self.name, self.surname)

students/forms.py
# -*- coding: utf-8 -*-
from django import forms

from students.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        labels = {'name': "Имя",
                  'surname': "Фамилия",
                  'date_of_birth': "Дата рождения",
                  'phone': "Телефон",
                  'address': "Адрес",
                  'course': "Курсы"
                  }

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required': 'Поле {fieldname} обязательно должно быть заполнено!'.format(
                fieldname=field.label)}
        self.base_fields['course'].help_text = ('Удерживайте нажатой кнопку "Control", или \
        "Command" на Mac, чтобы выбрать более одного курса. Должен быть выбран хотя бы один курс.')

students/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from students.models import Student


class StudentListView(ListView):
    model = Student

    def get_queryset(self):
        qs = super(StudentListView, self).get_queryset()
        course_id = self.request.GET.get('course_id', None)
        if course_id:
            qs = qs.filter(courses__id=course_id)
        return qs


class StudentDetailView(DetailView):
    model = Student


class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list')

    def form_valid(self, form):
        super_valid = super(StudentCreateView, self).form_valid(form)
        messages.success(self.request,
                         u'Студент {} {} успешно добавлен.'.format(self.object.name, self.object.surname))
        return super_valid

    def get_context_data(self, **kwargs):
        context = super(StudentCreateView, self).get_context_data(**kwargs)
        context.update({
            "title": u'Создание нового студента'
        })
        return context


class StudentUpdateView(UpdateView):
    model = Student
    success_url = '/students/edit/%(id)d/'

    def form_valid(self, form):
        messages.success(self.request, u'Данные изменены.')
        return super(StudentUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(StudentUpdateView, self).get_context_data(**kwargs)
        context.update({
            "title": u'Редактирование данных студента'
        })
        return context


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list')

    def delete(self, request, *args, **kwargs):
        delete_super = super(StudentDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request,
                         u'Студент {} {} был удален.'.format(self.object.name, self.object.surname))
        return delete_super

students/templates/apply.html
{% extends "students/base.html" %}


{% block title%}
	APPLY [!] {{ student.name }} {{student.surname}} - pyBursa
{% endblock title %}


{% block main_content %}
			<h1>{{ student.name }} {{student.surname}}</h1>
			
		    <div class="row">
		    <form method='post'> 
		    	{% csrf_token %}
		    	{{ form.as_p }}
		    	<input type="submit">
		    </form>
		    <br/>
		   
		    </div>
{% endblock main_content %}

students/templates/detail.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %}Студенты{% endblock %}


{% block nav_stud%}active{% endblock %}


{% block main_content%}



    <div class="container">

    {% include "now.html" %}

      <div class="panel panel-default">
        <!-- Default panel contents -->
        <align="center">
        <div class="panel-heading" align="center"><h3>Список студентов</h3></div>


        <!-- Table -->

        <table class="table">
         <thead>
            <tr>
            <th> <div align="center"><h5>#</h5></div></th>
            <th> <div align="center"><h5>Фамилия имя</h5></div></th>
            <th> <div align="center"><h5>Адрес</h5></div></th>
            <th> <div align="center"><h5>Скайп</h5></div></th>
            <th> <div align="center"><h5>Курсы</h5></div></th>
           </tr>
         </thead>

         <tbody>
         {% for student in students %}

         <tr>
         <td align="center">{{ forloop.counter }}</td>
         <td align="center" style="vertical-align:middle"><p><a href="/students/{{ student.id }}/">{{ student.surname }} {{ student.name }}</a></p></td>
         <td align="center" style="vertical-align:middle"><p>{{ student.addr }}</p></td>
         <td align="center" style="vertical-align:middle"><p>{{ student.skype }}</p></td>
         <td align="center" style="vertical-align:middle"><p>
             {% for theme in student.courses.all %}
                 <a href="/courses/{{theme.id}}/"> {{ theme }}</a>
             {% endfor %}
         </p></td>
         </tr>
         {% endfor %}

         </tr>
         </tbody>

        </table>
      </div>
    </div>

{% endblock main_content%}

students/templates/detail_info.html
{% extends "layout.html" %}

{% block title %}
Detail info 
{% endblock %}

{% block content %}

<div class="detail-info">
  <h2 class="h2-center">Информация о студенте</h2>
    <div>
      <table class="table table-striped table-style" style="width:100%">
        <tr>
          <th>Имя</th>
          <td>{{ student.name|upper }}</td>
        </tr>

        <tr>
          <th>Фамилия</th>
          <td>{{ student.surname }}</td>
        </tr>

        <tr>
          <th>Дата рождения</th>
          <td>{{ student.birthday }}</td>
        </tr>

        <tr>
          <th>Почта</th>
          <td>{{ student.email }}</td>
        </tr>

        <tr>
          <th>Телефон</th>
          <td>{{ student.phone_num }}</td>
        </tr>

        <tr>
          <th>Адрес</th>
          <td>{{ student.address }}</td>
        </tr>

        <tr>
          <th>Логин skype</th>
          <td>{{ student.skype }}</td>
        </tr>

        <tr>
          <th>Курсы</th>
          <td>
            {% for course in student.all_courses %}
            <a href="{% url 'courses:show' course.id %}">{{ course.title }}</a><br>
            {% endfor %}
          </td>
        </tr>
      </table>
    </div>
</div>
{% endblock %}

students/templates/list_students.html
{% extends "base_students.html" %}


{% block additional-info %}
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
        {{ message }}
      </div>
    {% endfor %}
  </ul>
{% endif %}
<a class="btn btn-primary active" href="{% url 'students:add_student' %}" role="button">
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
Добавить нового студента
</a>
{% endblock %}


{% block page-header %}Список студентов{% endblock %}


{% block page-content %} 
<thead>
  <tr>
    <th>№</th>
    <th>фамилия, имя</th>
    <th>адрес</th>
    <th>skype</th>
    <th>курсы</th>
  </tr>
</thead>
<tbody>
  {% csrf_token %}
  {% for student in students %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td><a href="{% url 'students:student' student.id %}">
            {{ student.surname }} {{ student.name }}
          </a>
      </td>
      <td>{{ student.address }}</td>
      <td>{{ student.skype }}</td>
      <td>
        {% for course in student.courses.all%}
          <a href="{% url 'courses:course_description' course.id %}">{{ course }}</a></br>
        {% endfor %}
      </td>
      <td>
         <a class="btn btn-primary active" 
            href="{% url 'students:edit_student' student.id %}" 
            role="button">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Изменить
         </a>
      </td>
      <td>
         <a class="btn btn-primary active" 
            href="{% url 'students:remove_student' student.id %}" 
            role="button">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            Удалить
         </a>
      </td>
    </tr>
  {% endfor %} 
</tbody>
{% endblock %}

students/templates/now.html
    <p align="right">
    <span  class="label label-primary">Стань студентом сейчас!</span>
    <br />
    <br />
    </p>

students/templates/oneofstudent.html
{% extends "students/base.html" %}


{% block title%}
	{{ student.name }} {{student.surname}} - pyBursa
{% endblock title %}


{% block main_content %}
			<h1>{{ student.name }} {{student.surname}}</h1>
			
		      <!-- Table -->
		      <table class="table">
		        <tbody>
		        <tr>
		          	<td>дата рождения</td>
		            <td>{{ student.date_of_birth }}</td>
		        </tr>
		        <tr>
		          	<td>адрес</td>
		            <td>{{ student.address }}</td>
		        </tr>
		        <tr>
		          	<td>почта</td>
		            <td>{{ student.email }}</td>
		        </tr>
		        <tr>
		          	<td>skype</td>
		            <td>{{ student.skype }}</td>
		        </tr>
		        <tr>
		          	<td>телефон</td>
		            <td>{{ student.phone }}</td>
		        </tr>
		        <tr>
		          	<td>курсы</td>
		            <td>
		            	{% for c in student.courses %}
			            	<a href="{% url "courses:oneof" c.id %}">{{ c }}</a> <br />
			            {% endfor%}
		            </td>
		        </tr>
		        <tr>
		          	<td></td>
		            <td>{{ student. }}</td>
		        </tr>
		        </tbody>
		      </table>
{% endblock main_content %}

students/templates/remove_student.html
{% extends "base_students.html" %}


{% block page-header %}Студент {{ student.fullname }} будет удален{% endblock %}


{% block page-content %}
<form method="post" > 
  {% csrf_token %}    
  <input type="submit" value="Удалить"> 
</form>   
{% endblock %}            

       

      
    

 

students/templates/student_add.html
{% extends "base.html" %}


{% block title %}Добавить студента{% endblock title %}


{% block nav %}{% include "nav.html" with active_students='active' %}{% endblock nav %}


{% block jumbotron %}{% endblock jumbotron %}

{% block table %}
<h2>Добавить студента</h2>
<div class="table-responsive">

<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Добавить студента">
</form>

</div>
{% endblock table %}

students/templates/student_delete.html
{% extends "base.html" %}


{% block title %}Отредактировать данные студента{% endblock title %}


{% block nav %}{% include "nav.html" with active_students='active' %}{% endblock nav %}


{% block jumbotron %}{% endblock jumbotron %}

{% block table %}
<h2>Удалить студента {{ student.first_name }} {{ student.surname }}?</h2>
<div class="table-responsive">

<form method="post">
{% csrf_token %}
<input type="submit" value="Удалить">
</form>

</div>
{% endblock table %}

students/templates/student_detail.html
{% extends "base.html" %}


{% block title %}{{stud.first_name}} {{stud.surname}} - студент Pybursa на курсах:
    {% for c in stud.course.all %}
        {{c.name}}{% if stud.course.all|length != forloop.counter %}, {% else %}{% endif %}
    {% endfor %}
{% endblock title %}


{% block nav %}{% include "nav.html" with active_students='active' %}{% endblock nav %}


{% block jumbotron %}{% endblock jumbotron %}

{% block table %}
<p><a href="{% url 'student_list' %}">Вернуться к списку</a></p>
<h2>{{stud.first_name}} {{stud.surname}}</h2>
<div class="table-responsive">
<table class="table table-hover">
  <tbody>
    <tr data-href="http://google.com">
      <th scope="row">Дата рождения</th>
      <td>{{stud.birdth_date|date:"d.m.Y"}}</td>
    <tr>
      <th scope="row">Адрес</th>
      <td>{{stud.adress}}</td>
    </tr>
    <tr>
      <th scope="row">Почта</th>
      <td>{{stud.email}}</td>
    </tr>
    <tr>
      <th scope="row">Логин skype</th>
      <td>{{stud.skype}}</td>
    </tr>
    <tr>
      <th scope="row">Телефон</th>
      <td>{{stud.phone}}</td>
    </tr>
    <tr>
      <th scope="row">Курсы</th>
      <td>{% for c in stud.course.all %}
          <a href="{% url 'course' c.id %}">{{c.name}}</a><br />{% endfor %}</td>
    </tr>
  </tbody>
</table>
</div>
{% endblock table %}

students/templates/student_edit.html
{% extends "base.html" %}


{% block title %}Отредактировать данные студента{% endblock title %}


{% block nav %}{% include "nav.html" with active_students='active' %}{% endblock nav %}


{% block jumbotron %}{% endblock jumbotron %}

{% block table %}
<h2>Отредактировать данные студента</h2>
<div class="table-responsive">

<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Редакрировать данные">
</form>

</div>
{% endblock table %}

students/templates/student_list.html
{% extends "base.html" %}


{% block title %}Список студентов Pybursa на всех курсах{% endblock title %}


{% block nav %}{% include "nav.html" with active_students='active' %}{% endblock nav %}


{% block jumbotron %}{% endblock jumbotron %}


{% block table %}
<h2>Список студентов</h2><br />
    {% if messages %}
        <div class="alert alert-success" role="alert">
    {% for message in messages %}
        {{ message }}
    {% endfor %}
        </div>
    {% endif %}
<p><a class="btn btn-primary glyphicon glyphicon-plus"
      href="{% url 'student_add' %}" role="button"> Добавить студента</a></p><br />
<div class="table-responsive">
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th>Фамилия Имя</th>
        <th>Адрес</th>
        <th>Skype</th>
        <th>Курсы</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>{% for st in stud %}
        <tr data-href="http://google.com">
            <th scope="row">{{st.id}}</th>
            <td><a href="{% url 'student_detail' st.id %}">{{st.first_name}} {{st.surname}}</a></td>
            <td>{{st.adress}}</td>
            <td>{{st.skype}}</td>
            <td><ul>{% for c in st.course.all %}
                <li><a href="{% url 'course' c.id %}">{{c.name}}</a></li>{% endfor %}
                </ul></td>
            <td><a class="btn btn-primary glyphicon glyphicon-pencil"
                   href="{% url 'student_edit' st.id %}" role="button"> Изменить</a></td>
            <td><a class="btn btn-primary glyphicon glyphicon-remove"
                   href="{% url 'student_delete' st.id %}" role="button"> Удалить</a></td>
        <tr>{% endfor %}
    </tbody>
</table>
</div>
{% endblock table %}

students/templates/students.html
{% extends "students/base.html" %}


{% block title%}
	Студенты курса {{ course.name }} - pyBursa
{% endblock title %}


{% block main_content %}		
			<ol class="breadcrumb">
			  <li class="active">Список студентов</li>
			</ol>
			
			 {% if messages %}
		    	<ul class="messages">
		    	{% for message in messages %}
		    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
		    			{{ message }}
		    		</li>
		    	{% endfor %}
		    	<ul>
		    {% endif %}
		    <br />
		    </ul>
			<a href="{% url "students:add" %}">[+] добавить студента</a>
 			<div class="panel panel-default">
		      <!-- Default panel contents -->
		      <div class="panel-heading">План курса</div>

		      <!-- Table -->
		      <table class="table">
		        <thead>
		          <tr>
		          	 <th scope="row">#</th>
		            <th>фамилия имя</th>
		            <th>дата рождения</th>
		            <th>адрес</th>
		            <th>skype</th>
		            <th>курсы</th>
		            <th></th>
		            <th></th>
		          </tr>
		        </thead>
		        <tbody>
		        {% for s in students %}
		          <tr>
		          	<td scope="row">{{ s.id }}</td>
		            <td><a href="{% url "students:oneof" s.id %}">{{ s.surname|upper }} {{ s.name }}</a></td>
		            <td>{{ s.date_of_birth|date:"SHORT_DATE_FORMAT" }}</td>
		            <td>{{ s.address|default:"not set"}}</td>
		            <td>{{ s.skype|truncatechars:9 }}</td>

		            <td>
			            {% for c in s.courses %}
			            	<a href="{% url "courses:oneof" c.id %}">{{ c }}</a> <br />
			            {% endfor%}
		            </td>
		            <td>
		            	<a href="{% url "students:edit" s.id %}">edit</a>
		            </td>
		             <td>
		            	<a href="{% url "students:delete" s.id %}">delete</a>
		            </td>
		          </tr>
		        {% endfor%}
		        </tbody>
		      </table>
		    </div>
{% endblock main_content %}		

students/templates/students_list.html
{% extends "layout.html" %}

{% block section %}page-students{% endblock %}

{% block title %}
Students
{% endblock %}

{% block extra_menu %}
  <li>
    <a href="{% url 'students:student-add' %}">Новый студент</a>
  </li>
{% endblock %}

{% block content %}
<div class="course-info">

  <h2>Список студентов</h2>

  <div>
    <div class="students">
      <table class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>№</th>
          <th>Фамилия Имя</th>
          <th>Адрес</th>
          <th>Skype</th>
          <th>Курсы</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr>
          <td>{{ student.id }}</td>
          <td><a href="{% url 'students:student-detail' student.id %}">
              {{ student.surname}} {{ student.name}}
              </a>
          </td>
          <td>{{ student.address }}</td>
          <td>{{ student.skype }}</td>
          <td>{% for course in student.all_courses %}
            <a href="{% url 'courses:show' course.id %}">{{ course.title }}</a><br>
          {% endfor %}</td>
          <td>
            <a href="{% url 'students:student-edit' student.id %}">
              <span class="glyphicon glyphicon-pencil"></span>
            </a>
          </td>
          <td>
            <a href="{% url 'students:student-delete' student.id %}">
              <span class="glyphicon glyphicon-trash"></span>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}